// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR KEY',
    appId: '1:488443205841:web:7db10f23594664cc3f8df0',
    messagingSenderId: '488443205841',
    projectId: 'talkg-app',
    authDomain: 'talkg-app.firebaseapp.com',
    databaseURL: 'https://talkg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'talkg-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR KEY',
    appId: '1:488443205841:android:9f61c87f4b95636c3f8df0',
    messagingSenderId: '488443205841',
    projectId: 'talkg-app',
    databaseURL: 'https://talkg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'talkg-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:488443205841:ios:8546e84e04c2a4e53f8df0',
    messagingSenderId: '488443205841',
    projectId: 'talkg-app',
    databaseURL: 'https://talkg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'talkg-app.appspot.com',
    androidClientId: '488443205841-kfa6crqh3dlp8pmfpln7gfvkqlvnri0e.apps.googleusercontent.com',
    iosClientId: '488443205841-ppb981j9ng25bqljlhctguq561o2snjn.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '',
    appId: '1:488443205841:ios:272d9a2c614b90ee3f8df0',
    messagingSenderId: '488443205841',
    projectId: 'talkg-app',
    databaseURL: 'https://talkg-app-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'talkg-app.appspot.com',
    androidClientId: '488443205841-kfa6crqh3dlp8pmfpln7gfvkqlvnri0e.apps.googleusercontent.com',
    iosClientId: '488443205841-oaoru8vbmu6crv5bq9ovcfmmho1hpdij.apps.googleusercontent.com',
    iosBundleId: 'com.example.talkg.RunnerTests',
  );
}
